### ISSUE TITLE
TwitchLoginInfo is not created nor saved automatically

### ISSUE THREAD

**Issue by oksoff** [brian91292/StreamCore#6]
Overview:
TwitchLoginInfo.ini config is not automatically created and is not used unless manually created.

BS version: 1.5.0
StreamCore 2.2.0 from MA

Description:
When you first start the game and/or enter twitch credits in GUI no UserData/StreamCore/TwitchLoginInfo.ini is created.
On next game restart options entered in UI are reset to default state (== not defined)
If you manually create UserData/StreamCore/TwitchLoginInfo.ini with contents:
TwitchChannelName=[twitch_name_there]
It will correctly load twitch chat on next game start.

**Comment by oksoff** [comment]
Log when twitchlogininfo does not exist
[_latest.log](https://github.com/brian91292/StreamCore/files/3827205/_latest.log)

**Comment by brian91292** [comment]
Fixed in 3d41b6441c700feef398069f991aeb9c84ce32e3
